services:
  - type: web
    name: infosnap
    env: python
    plan: starter    
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=1 --threads=1 --timeout 120"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
